### ISSUE TITLE
tag和problem对应关系

### ISSUE THREAD

**Issue by lluckydog** [Linzecong/LPOJ#123]
你好，我想请教一下有关tag和problem之间的关系，看代码似乎是相互独立的两个model，那么是怎么保证tag和problem的对应关系的呢？例如，我添加了一道题目中带有之前没有的tag，我怎么保证tag中也会对应添加上这个tag呢？是通过管理者自己维护嘛？有什么相对比较方便的方法吗？希望可以得到回到，谢谢！

**Comment by Linzecong** [comment]
全表扫描……

**Comment by lluckydog** [comment]
好的，谢谢0.0
