### ISSUE TITLE
博客爬虫数据泄露用户真实姓名

### ISSUE THREAD

**Issue by xMuu** [Linzecong/LPOJ#54]
在 Demo 爬到的博客数据里面，居然直接跟用户的真实姓名一同公布，这是不是泄露了用户隐私？页面上写的是 UserName ，而展示的数据却是人名。

**Comment by DirtyBat** [comment]
还行吧，主要是集训队内部用，互相都认识

**Comment by xMuu** [comment]
> 还行吧，主要是集训队内部用，互相都认识

那请问有对数据做反爬处理吗？

**Comment by Linzecong** [comment]
爬虫数据是人为录入的，可以不使用真名。方便我校管理，使用了真名而已。如需要部署，一般部署在内网，不涉及隐私。数据API全部开放，要拿数据直接访问API，不阻止爬虫
