### ISSUE TITLE
程序调用测试程序支持

### ISSUE THREAD

**Issue by yangshao** [Linzecong/LPOJ#77]
leetcode有些题目是让你实现一些函数，然后后台判题是用另外一个代码去调用这个函数，从而产生一些输出，实现判题，请问下lpoj支持这个功能么

**Comment by DirtyBat** [comment]
支持~

**Comment by yangshao** [comment]
@DirtyBat 请问怎么操作呢， 新建题目的时候只看到添加用户需要实现的函数和输入输出数据集。

**Comment by DirtyBat** [comment]
@yangshao 请参照文档
https://docs.lpoj.cn/doc/judger.html#special-judge
模板题部分

**Comment by yangshao** [comment]
@DirtyBat 看了下文档，还是没明白输入输出怎么处理。 非模板题需要自己在main函数里处理，模板题的话，输入输出是在自定义模板的main函数里处理？
